### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by dupham2206** [xinzwang/LMOT#6]
Hi, I'm very interested in your dataset and would love to conduct research using it. However, as I'm not based in China, accessing Baidu Drive to download the data is quite challenging. Would it be possible for you to provide the data through a more internationally accessible platform

**Comment by XilunZhangRobo** [comment]
Hi, were you able to download it from other platform, I am having the same issue here. Thanks

**Comment by abdulkarimatrash** [comment]
same problem here, @dupham2206  @XilunZhangRobo @xinzwang  any updates on downloading the dataset?
